name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout í»ï¸
      uses: actions/checkout@v2.3.1

    - name: Install and build í´§
      run: |
        npm install
        npm run build

    - name: Deploy íº€
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: distname: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ï¿½ï¿½ï¿½ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and build ï¿½ï¿½ï¿½
        run: |
          npm install
          npm run build

      - name: Deploy ï¿½ï¿½ï¿½
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
